### ISSUE TITLE
Node 10 Type Error - fs asynchronous function without callback

### ISSUE THREAD

**Issue by R4mpancy** [jasonkneen/TiTh#10]
Saw this warning when using the module before, but never forced to address it until setting up a new machine with Node 10 installed.
It happens due to fs calling an asynchronous function without callback.

[Link to deprecation in Node docs](https://nodejs.org/api/deprecations.html#deprecations_dep0013_fs_asynchronous_function_without_callback)

I'll try sometime to get another pull request together to address this.

**Comment by jasonkneen** [comment]
thanks!
