### ISSUE TITLE
Does not work with Node LTS (12.16.2)

### ISSUE THREAD

**Issue by ffMathy** [jasonkneen/TiTh#13]
`tith set myproject android`

> 
> fs.js:35
> } = primordials;
>     ^
> 
> ReferenceError: primordials is not defined
>     at fs.js:35:5
>     at req_ (C:\Source\myproject\node_modules\natives\index.js:143:24)      
>     at Object.req [as require] (C:\Source\myproject\node_modules\natives\index.js:55:10)
>     at Object.<anonymous> (C:\Source\myproject\node_modules\graceful-fs\fs.js:1:37)
>     at Module._compile (internal/modules/cjs/loader.js:1156:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)   
>     at Module.load (internal/modules/cjs/loader.js:1000:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
>     at Module.require (internal/modules/cjs/loader.js:1042:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1   
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jasonkneen** [comment]
If you're able to fix and do a PR that would be awesome.

**Comment by ffMathy** [comment]
Not sure why it happens. From the stack-trace it seems to happen inside "graceful-fs", but I don't see a direct reference to it.

**Comment by bennett** [comment]
I am also having this issue.

**Comment by jasonkneen** [comment]
Fixed, thank you @tockv!
