### ISSUE TITLE
Unable to select a theme after a fresh install of TiTh

### ISSUE THREAD

**Issue by rumbleyam** [jasonkneen/TiTh#7]
A fresh install of TiTh no longer functions as intended due to an update to the dependency Commander.  When running `tith set <theme name>` it looks like the arguments are ignored.  Only `Current Alloy theme is: <theme name>` is printed.

Changing the package.json so that it looks for Commander `~2.6.0` instead of `^2.6.0` will select a compatible version of Commander.

**Comment by jasonkneen** [comment]
PR welcome

**Comment by jasonkneen** [comment]
Thanks for this -- fixed today.
